ARG NODE_VERSION=18-alpine3.18

FROM node:${NODE_VERSION} AS node

FROM node as client-local-build

LABEL version="1.0"
LABEL description="React Frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . /app

CMD ["npm", "run", "start"]
