# Generated by Django 6.1.1 on 2026-09-13 15:21

import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+254712345678', max_length=25, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='Say something about yourself', max_length=255, verbose_name='About Me')),
                ('license_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Real Estate License')),
                ('profile_photo', models.ImageField(default='/profile_default.png', max_length=255, upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=255, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(blank=True, default='Kenya', max_length=255, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=255, null=True, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you looking for a property', verbose_name='Buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you selling a property', verbose_name='Seller')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you an Agent', verbose_name='Agent')),
                ('top_agent', models.BooleanField(default=False, help_text='Are you a Top Agent', verbose_name='Top Agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Reviews')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
