# Generated by Django 6.1.1 on 2026-09-13 15:59

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='KE', max_length=255, null=True, verbose_name='Country'),
        ),
    ]
