# Generated by Django 4.0.5 on 2022-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_agent',
            field=models.BooleanField(default=False, help_text='Are you a Top Agent', verbose_name='Top Agent'),
        ),
    ]
