#!/bin/bash

set -o errexit

set -o nounset

celery -A real_estate

worker_ready(){
    celery worker inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers not available :-('
    sleep 1

done
>&2 echo 'Celery workers are available and ready!...:-)'

flower \
    --app=real_estate \
    --broker="${CELERY_BROKER}"