# Generated by Django 4.0.5 on 2022-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior_sample1.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior_sample2.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior_sample3.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior_sample4.jpg', null=True, upload_to=''),
        ),
    ]
